<?php
/**
 * @link          http://cakephp.org CakePHP(tm) Project
 * @package       app.View.Pages
 * @since         CakePHP(tm) v 0.10.0.1076
 */

?>
<h1>Related BLUEPRINT WP10 data sites</h1>
<h3>
<ul>
	<li>Supporting WP10 data is available at
	<ul><li><a href="ftp://ftp.ebi.ac.uk/pub/databases/blueprint/blueprint_Epivar/" target="_blank">ftp://ftp.ebi.ac.uk/pub/databases/blueprint/blueprint_Epivar/</a></li></ul></li>
	<li>UCSC track hub for WP10 chromatin states generated by BLUEPRINT project in hg19 human genome
	<ul><li><a href="http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&hubUrl=http://mcahematopoiesis.bioinfo.cnio.es/carrillo_et_al_NAR/hub.txt" target="_blank">Direct link to UCSC genome browser</a></li></ul>
	<ul><li><a href="http://mcahematopoiesis.bioinfo.cnio.es/carrillo_et_al_NAR/hub.txt" target="_blank">Direct link to the track hub (based on hg19 human genome), to be used in capable genomic browsers</a></li></ul></li>
</ul>
</h3>
